=== cookepoli/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!-- ==========================================================================
  The Root Element: student_directory

  The student_directory (root) element must contain one or more student elements.
  ============================================================================-->

<!ELEMENT student_directory (student)+>

<!-- ==========================================================================
  The student container element must contain one FirstName, MiddleName, LastName,
  PrefName, StudentID, email, phone, year, GPA, major, minor, status, advisor,
  enroll_date, and grad_date element.
  ===============================================================================-->

<!ELEMENT student (FirstName,MiddleName,LastName,PrefName,enrollment_info, contact_info, department_info)>

<!-- ============================================================================
  The enrollment_info element must contain information about the student's enrollment status:
  Their ID number, year, status, date of enrollment, and graduation date.
  ===============================================================================-->

<!ELEMENT enrollment_info (StudentID,enroll_date,grad_date)>

<!-- ============================================================================
  The contact_info element must contain the student's email and phone.
  ===============================================================================-->

<!ELEMENT contact_info (email,phone)>

<!-- ============================================================================
  The department_info element must contain information about the student's department:
  Their GPA, major, minor, and academic advisor. Each student must have at least one
  major (but can have more), and may have 0 or more minors.
  ===============================================================================-->

<!ELEMENT department_info (GPA,major+,minor*,advisor)>

<!-- =============================================================================
  The elements below all may contain parsed character data, except for the
  year and status elements which should be empty. These two elements use attributes
  instead of content.
  ===============================================================================-->

<!ELEMENT FirstName     (#PCDATA)>    <!-- FirstName element must be empty or contain parsed character data.-->
<!ELEMENT MiddleName    (#PCDATA)>    <!-- MiddleName element must be empty or contain parsed character data.-->
<!ELEMENT LastName      (#PCDATA)>    <!-- LastName element must be empty or contain parsed character data.-->
<!ELEMENT PrefName      (#PCDATA)>    <!-- PrefName element must be empty or contain parsed character data.-->
<!ELEMENT StudentID     (#PCDATA)>    <!-- StudentID element must be empty or contain parsed character data.-->
<!ELEMENT email         (#PCDATA)>    <!-- email element must be empty or contain parsed character data.-->
<!ELEMENT phone         (#PCDATA)>    <!-- phone element must be empty or contain parsed character data.-->
<!ELEMENT GPA           (#PCDATA)>    <!-- GPA element must be empty or contain parsed character data.-->
<!ELEMENT major         (#PCDATA)>    <!-- major element must be empty or contain parsed character data.-->
<!ELEMENT minor         (#PCDATA)>    <!-- minor element must be empty or contain parsed character data.-->
<!ELEMENT advisor       (#PCDATA)>    <!-- advisor element must be empty or contain parsed character data.-->
<!ELEMENT enroll_date   (#PCDATA)>    <!-- enroll_date element must be empty or contain parsed character data.-->
<!ELEMENT grad_date     (#PCDATA)>    <!-- grad_date element must be empty or contain parsed character data.-->


<!-- ==============================================================================
  The enrollment_info element contains two attributes used to store information about
  the student's year and enrollment status. Attributes are used instead of elements
  because the set of possible data contained is fixed. These
  attributes are both required.
  =================================================================================-->

<!ATTLIST enrollment_info
          year (First-Year|Second-Year|Third-Year|Fourth-Year|Non-Traditional) #REQUIRED>

<!ATTLIST enrollment_info
          status (full-time|part-time|graduated|withdrawn) #REQUIRED>

<!-- ==============================================================================
  The student element contains an attribute number that is required. This indicates
  the index of the student in the database, with the first student having an index of 1.
  This attribute is required for each student element. In this case, the tag
  must be (unparsed) character data.
  =================================================================================-->

<!ATTLIST student
          number CDATA #REQUIRED>

=== cookepoli/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="../style.css"?>

<!DOCTYPE students SYSTEM "../student.dtd" [
  <!ENTITY student "">
]>

<student_directory>

<student>
  <FirstName>Gordon</FirstName>
  <MiddleName>Matthew</MiddleName>
  <LastName>Sumner</LastName>
  <PrefName>Sting</PrefName>
  <StudentID>1234567</StudentID>
  <email>sting@thepolice.com</email>
  <phone>212.123.4567</phone>
  <year>first year</year>
  <GPA>4.0</GPA>
  <major>Music</major>
  <minor>English</minor>
  <status>full-time</status>
  <advisor>Andy Summers</advisor>
  <enroll_date>08-25-1969</enroll_date>
  <grad_date>05-01-1973</grad_date>
</student>

<student>
  <FirstName>Kim</FirstName>
  <MiddleName/>
  <LastName>Thayil</LastName>
  <PrefName/>
  <StudentID>4567890</StudentID>
  <email>kim@soundgarden.com</email>
  <phone>206.123.4567</phone>
  <year>second year</year>
  <GPA>3.0</GPA>
  <major>Philosophy</major>
  <minor>Music</minor>
  <status>full-time</status>
  <advisor>Chris Cornell</advisor>
  <enroll_date>08-25-1978</enroll_date>
  <grad_date>05-01-1982</grad_date>
</student>

<student>
  <FirstName>Saul</FirstName>
  <MiddleName/>
  <LastName>Hudson</LastName>
  <PrefName>Slash</PrefName>
  <StudentID>8302438</StudentID>
  <email>slash@gnr.com</email>
  <phone>213.456.8392</phone>
  <year>fourth year</year>
  <GPA>2.0</GPA>
  <major>Music</major>
  <minor>Criminal Justice</minor>
  <status>part-time</status>
  <advisor>Axl Rose</advisor>
  <enroll_date>08-25-1983</enroll_date>
  <grad_date>05-01-1987</grad_date>
</student>

<student>
  <FirstName>Emily</FirstName>
  <MiddleName/>
  <LastName>Kokal</LastName>
  <PrefName/>
  <StudentID>2983928</StudentID>
  <email>emily@warpaint.com</email>
  <phone>213.123.7654</phone>
  <year>third year</year>
  <GPA>3.8</GPA>
  <major>Political Science</major>
  <minor>Law</minor>
  <status>full-time</status>
  <advisor>Jenny Lee Lindberg</advisor>
  <enroll_date>08-25-1998</enroll_date>
  <grad_date>05-01-2002</grad_date>
</student>

<student>
  <FirstName>Mike</FirstName>
  <MiddleName/>
  <LastName>Inez</LastName>
  <PrefName/>
  <StudentID>7645726</StudentID>
  <email>mike@aic.com</email>
  <phone>213.444.3323</phone>
  <year>second year</year>
  <GPA>4.0</GPA>
  <major>Business Management</major>
  <minor>Math</minor>
  <status>full-time</status>
  <advisor>Jerry Centrell</advisor>
  <enroll_date>08-25-1984</enroll_date>
  <grad_date>05-01-1988</grad_date>
</student>

</student_directory>
